-- Migration: Create monthly_budgets table
-- Description: Monthly income and budget overview per user
-- Dependencies: Requires Supabase Auth (auth.uid())

-- Create monthly_budgets table
CREATE TABLE IF NOT EXISTS "public"."monthly_budgets" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "month" "text" DEFAULT ''::"text" NOT NULL,
    "income" numeric DEFAULT '0'::numeric NOT NULL
);

-- Set table owner
ALTER TABLE "public"."monthly_budgets" OWNER TO "postgres";

-- Add table comment
COMMENT ON TABLE "public"."monthly_budgets" IS 'Monthly income and budget overview';

-- Create auto-incrementing ID
ALTER TABLE "public"."monthly_budgets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."monthly_budgets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Add primary key constraint
ALTER TABLE ONLY "public"."monthly_budgets"
    ADD CONSTRAINT "monthly_budgets_pkey" PRIMARY KEY ("id");

-- Enable Row Level Security
ALTER TABLE "public"."monthly_budgets" ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "monthly_budgets_select_policy" ON "public"."monthly_budgets" 
    FOR SELECT TO "authenticated" 
    USING (("auth"."uid"() = "user_id"));

CREATE POLICY "monthly_budgets_insert_policy" ON "public"."monthly_budgets" 
    FOR INSERT TO "authenticated" 
    WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "monthly_budgets_update_policy" ON "public"."monthly_budgets" 
    FOR UPDATE TO "authenticated" 
    USING (("auth"."uid"() = "user_id")) 
    WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "monthly_budgets_delete_policy" ON "public"."monthly_budgets" 
    FOR DELETE TO "authenticated" 
    USING (("auth"."uid"() = "user_id"));

-- Grant permissions
GRANT ALL ON TABLE "public"."monthly_budgets" TO "anon";
GRANT ALL ON TABLE "public"."monthly_budgets" TO "authenticated";
GRANT ALL ON TABLE "public"."monthly_budgets" TO "service_role";

GRANT ALL ON SEQUENCE "public"."monthly_budgets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."monthly_budgets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."monthly_budgets_id_seq" TO "service_role";